server:
  port: 8084

logging:
  level:
    com:
      amazonaws:
        internal:
          InstanceMetadataServiceResourceFetcher: error
        util:
          EC2MetadataUtils: error

spring:
  jpa:
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: none
  datasource:
    url: jdbc:mysql://localhost:3306/promocaodb
    username: admin
    password: admin
    driver-class-name: com.mysql.jdbc.Driver

cloud:
  aws:
    region:
      static: us-east-2
      auto: false
    stack:
      auto: false
    credentials:
      access-key: <ACCESS-KEY>
      secret-key: <SECRET-KEY>
    end-point:
      uri: <QUEUE-URL>